// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Clouds: typeof import('./src/components/Show/Clouds.vue')['default']
    Content: typeof import('./src/components/Show/Content.vue')['default']
    Earth: typeof import('./src/components/Show/Earth.vue')['default']
    Page: typeof import('./src/components/Page/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
  }
}
